In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
arr1=np.array(10)
arr1

array(10)

In [6]:
arr2=np.array([[0,1,2],[3,4,5],[6,7,8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
zeros=np.zeros(5)
zeros.dtype

dtype('float64')

In [8]:
arr2=np.array([[0,1,2],[3,4,5],[9,7,8],[3,5,6]])
arr2.shape


(4, 3)

In [9]:

arr2.dtype

dtype('int64')

In [3]:
swapped = np.swapaxes(arr2, 0, 1)
print(swapped)



[[0 3]
 [1 4]
 [2 5]]


In [2]:
import numpy as np

arr = np.arange(6)        # Create an array [0, 1, 2, 3, 4, 5]
arr2 = np.reshape(arr, (2, 3))  # Reshape it to 2 rows and 3 columns
print(arr2)


[[0 1 2]
 [3 4 5]]


In [ ]:
arr2=np.array([[1,6,2],[3,4,5],[9,7,8],[3,5,6]])
swaped = np.swapaxes(arr2, 0, 1)
swaped

array([[1, 3, 9, 3],
       [6, 4, 7, 5],
       [2, 5, 8, 6]])

In [ ]:
arr2.max()

np.int64(9)

In [ ]:
arr2.reshape(3,4)

array([[1, 6, 2, 3],
       [4, 5, 9, 7],
       [8, 3, 5, 6]])

In [1]:
import numpy as np

arr2 = np.linspace(1, 4, 8)
print(arr2)


[1.         1.42857143 1.85714286 2.28571429 2.71428571 3.14285714
 3.57142857 4.        ]


In [ ]:
import numpy as np
print(np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr[1])    
print(arr[-1])    

arr2 = np.array([[1, 2], [3, 4]])
print(arr2[0][1]) 

20
40
2


In [ ]:
a = np.arange(1, 10)
b = a.reshape(3, 3)          
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)     
print(x - y)     
print(x * y)     
print(x / y)     
print(x ** 2)    

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [ ]:
arr = np.array([1, 3, 7, 2, 9])

print(np.argmax(arr))  
print(np.argmin(arr))   
print(np.linspace(0, 1, 5))  
print(np.diff(arr))     

4
0
[0.   0.25 0.5  0.75 1.  ]
[ 2  4 -5  7]


In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x + y)     
print(x - y)     
print(x * y)     
print(x / y)     
print(x ** 2)    

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [ ]:
arr = np.array([1, 3, 7, 2, 9])

print(np.argmax(arr))   
print(np.argmin(arr))  
print(np.linspace(0, 1, 5))  
print(np.diff(arr))     

4
0
[0.   0.25 0.5  0.75 1.  ]
[ 2  4 -5  7]


In [ ]:
#self learning topic
arr = np.array([1, 3, 7, 2, 9])

print(np.argmax(arr))   
print(np.argmin(arr))  
print(np.linspace(0, 1, 5))  
print(np.diff(arr))     


4
0
[0.   0.25 0.5  0.75 1.  ]
[ 2  4 -5  7]


In [ ]:
#self learning topic
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)     
print(arr.size)

2
6
